#!/usr/bin/env bash
# Per-boot startup for app-cuisine.
# Brings up the Docker daemon (nested via fuse-overlayfs), the local Supabase stack,
# writes .env.local, and seeds a demo user + recipes. Idempotent: safe to re-run.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "${PROJECT_DIR}"

DEMO_EMAIL="chef@example.com"
DEMO_PASSWORD="Password123!"

echo "==> Configuring Docker to use fuse-overlayfs (nested-container friendly)"
sudo mkdir -p /etc/docker
echo '{
  "storage-driver": "fuse-overlayfs",
  "features": { "containerd-snapshotter": false }
}' | sudo tee /etc/docker/daemon.json >/dev/null

echo "==> Starting Docker daemon"
if ! pgrep -x dockerd >/dev/null 2>&1; then
  sudo nohup dockerd >/tmp/dockerd.log 2>&1 &
fi
for _ in $(seq 1 30); do
  if sudo docker info >/dev/null 2>&1; then break; fi
  sleep 1
done
sudo chmod 666 /var/run/docker.sock || true

# Allow same-bridge container-to-container traffic to bypass the host netfilter chains,
# which are unreliable in this nested environment and otherwise block DB connections.
echo "==> Relaxing bridge netfilter for container networking"
sudo sysctl -w net.bridge.bridge-nf-call-iptables=0 >/dev/null 2>&1 || true
sudo sysctl -w net.bridge.bridge-nf-call-ip6tables=0 >/dev/null 2>&1 || true

echo "==> Starting local Supabase stack"
if ! supabase status >/dev/null 2>&1; then
  supabase start
fi

echo "==> Writing .env.local from Supabase status"
STATUS_ENV="$(supabase status -o env)"
get() { echo "${STATUS_ENV}" | grep -E "^$1=" | head -1 | cut -d'=' -f2- | tr -d '"'; }
API_URL="$(get API_URL)"
PUBLISHABLE_KEY="$(get PUBLISHABLE_KEY)"
SECRET_KEY="$(get SECRET_KEY)"

cat > "${PROJECT_DIR}/.env.local" <<EOF
# Auto-generated by .cursor/start.sh for the local Supabase stack (dev only)
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SECRET_KEY}
ADMIN_USER_IDS=
LEGAL_CONTROLLER_NAME=Dev Local
LEGAL_CONTACT_EMAIL=dev@example.com
LEGAL_SUPABASE_REGION=local
EOF

echo "==> Ensuring demo user exists (${DEMO_EMAIL})"
curl -s -X POST "${API_URL}/auth/v1/admin/users" \
  -H "apikey: ${SECRET_KEY}" \
  -H "Authorization: Bearer ${SECRET_KEY}" \
  -H "Content-Type: application/json" \
  -d "{\"email\":\"${DEMO_EMAIL}\",\"password\":\"${DEMO_PASSWORD}\",\"email_confirm\":true}" \
  >/dev/null || true

echo "==> Seeding demo recipes"
DEMO_UID="$(curl -s "${API_URL}/auth/v1/admin/users" \
  -H "apikey: ${SECRET_KEY}" -H "Authorization: Bearer ${SECRET_KEY}" \
  | python3 -c "import sys,json;u=[x for x in json.load(sys.stdin).get('users',[]) if x['email']=='${DEMO_EMAIL}'];print(u[0]['id'] if u else '')")"
if [ -n "${DEMO_UID}" ]; then
  DB_CONTAINER="$(docker ps --format '{{.Names}}' | grep -E 'supabase_db' | head -1)"
  # Only seed when the user currently has no recipes (keeps this idempotent).
  EXISTING="$(docker exec -i "${DB_CONTAINER}" psql -U postgres -d postgres -tAc \
    "select count(*) from public.recipes where user_id = '${DEMO_UID}'" 2>/dev/null || echo 0)"
  if [ "${EXISTING}" = "0" ]; then
    sed "s/__DEMO_UID__/${DEMO_UID}/g" "${PROJECT_DIR}/.cursor/seed.sql" \
      | docker exec -i "${DB_CONTAINER}" psql -U postgres -d postgres >/dev/null
  fi
fi

echo "==> start.sh complete"
echo "    App:    http://localhost:3000  (login: ${DEMO_EMAIL} / ${DEMO_PASSWORD})"
echo "    Studio: $(get STUDIO_URL)"
